import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "@/styles/globals.css";
import { Providers } from "@/redux/provider";
import ScrollTopButton from "@/components/Layout-components/ScrollTop";
import ThemeWrapper from "@/components/Layout-components/ThemeWrapper";

const public_sans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={public_sans.className}>
        <Providers>
          <ThemeWrapper>
            {children}
            <ScrollTopButton />
          </ThemeWrapper>
        </Providers>
      </body>
    </html>
  );
}
